version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib
  matrix:
    - TARGET: neko,node
    - TARGET: flash,js
    - TARGET: cpp
    - TARGET: cs,java

matrix:
  fast_finish: true

branches:
  only:
    - develop

install:
  - cinst haxe -version 3.2.1 -y
  - RefreshEnv
  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"
  - haxelib git hxmake https://github.com/eliasku/hxmake.git
  - haxelib dev ecx .

build: off

test_script:
  - haxelib run hxmake test --override-test-target="%TARGET%"
